### ISSUE TITLE
Could the model be trained on multiple GPUs?

### ISSUE THREAD

**Issue by AXINLETTER** [yassersouri/task-driven-object-detection#1]

**Comment by yassersouri** [comment]
We have not tried it. But I assume with a bit of coding it should be possible to train on multiple gpus in "data parallel" setting.

**Comment by AXINLETTER** [comment]
Annotation problems in test set
Hello, the annotation information in the test set like: 
{"image_id": 445200, "category_id": 1, "score": 0.6065034866333008, "bbox": [380.34, 45.83, 86.32, 129.75], "COCO_category_id": 47}, which information means that this instance can complete that task? I can get the score of an instance about being able to complete a task through the model and how to calculate the accuracy ? Thx~

**Comment by AXINLETTER** [comment]
Annotation problems in test set.
Hello, the annotation information in the test set like:
{"license": 5, "file_name": "COCO_val2014_000000445200.jpg", "coco_url": "http://mscoco.org/images/445200", "height": 427, "width": 640, "date_captured": "2013-11-20 04:27:57", "flickr_url": "http://farm2.staticflickr.com/1147/5103880651_f3c1e2a721_z.jpg", "id": 445200}, and we use the model to get the detection result, like:
{"image_id": 445200, "category_id": 1, "score": 0.6065034866333008, "bbox": [380.34, 45.83, 86.32, 129.75], "COCO_category_id": 47},I can not understand which information means that this instance can complete that task in the anotation test set? I can get the score of an instance about being able to complete a task through the model but how to calculate the accuracy ? Thx~
