### ISSUE TITLE
object detector & pick best class

### ISSUE THREAD

**Issue by Philipflyg** [yassersouri/task-driven-object-detection#4]
Can you provide the codes related to the experiments of "object detector" and "pick best class"?

**Comment by yassersouri** [comment]
Hi, 
Sorry for the late response.

We have not released the code for the object detector and the pick-best-class baselines. And I currently don't have them anymore.

The pick-best-class baselines is just a short script that goes over the detections (https://github.com/coco-tasks/dataset/blob/master/detections_faster.json) and makes predictions using some statistics collected from the training set (https://github.com/coco-tasks/dataset/tree/master/annotations).

For the object detector baseline we used a third-party implementation of faster-rcnn and trained a detector for each task.

For details please refer to our description of each baseline in the paper.

(Also maybe @ykztawas can provide more details)
